<!DOCTYPE html>
<html dir="ltr" lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>Empregoh</title>
    <link href="../assets/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="../assets/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="../assets/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <link href="../assets/dist/css/style.min.css" rel="stylesheet">
    <link href="../css/style.css" rel="stylesheet">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>
<div class="preloader">
    <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
    </div>
</div>
<div>
    <?php \App\Controller\AbstractController::navbar();?>
    <div class="container-fluid">
        <div class="card-group">
            <div class="card border-right">
                <div class="card-body">
                    <?php main(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="../js/event.js"></script>
<script src="../assets/assets/libs/jquery/dist/jquery.min.js"></script>
<script src="../assets/libs/popper.js/dist/umd/popper.min.js"></script>
<script src="../assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="../assets/dist/js/app-style-switcher.js"></script>
<script src="../assets/dist/js/feather.min.js"></script>
<script src="../assets/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
<script src="../assets/dist/js/sidebarmenu.js"></script>
<script src="../assets/dist/js/custom.min.js"></script>
<script src="../assets/assets/extra-libs/c3/d3.min.js"></script>
<script src="../assets/assets/extra-libs/c3/c3.min.js"></script>
<script src="../assets/assets/libs/chartist/dist/chartist.min.js"></script>
<script src="../assets/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
<script src="../assets/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
<script src="../assets/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
<script src="../assets/dist/js/pages/dashboards/dashboard1.min.js"></script>
</body>
</html>

