<h4 class="card-title">Lista de Usuário</h4>
<table class="table table-striped table-hover">
    <thead class="thead-dark">
    <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Foto</th>
        <th>Cpf</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($users as $user) {
        echo "
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <a href='' class='btn btn-warning btn-sm'>Editar</a>    
                    <a href='' class='btn btn-danger btn-sm'>Excluir</a>    
                </td>
            </tr>
            ";
    }

    ?>
    </tbody>
</table>