<h4 class="card-title">Perfil do Usuário</h4>
<div class="row mt-5">
    <div class="col-md-6">
        <img src="" width="200px" alt="">
    </div>
    <div class="col-md-6">
        <div class="card card-body">
            <p>
                <?php ?>
                    <span class="badge badge-dark">Administrador</span>
                <?php ?>
            </p>
            <p>
                <strong>Nome: </strong>
            </p>
            <p>
                <strong>E-mail: </strong>
            </p>
            <p>
                <strong>Cpf: </strong>
            </p>
            <p>
                <strong>Último login: </strong>
                <?php
                ?>
            </p>
        </div>
