<form action="" method="post">
    <h4 class="card-title">Adicionar Veículos</h4>
    <label for="make">Marca</label>
    <input type="text" value="<?=$vehicle->getMake()?>"  name="make" id="make"  class="form-control">
    <br>

    <label for="model">Modelo</label>
    <input type="text" value="<?=$vehicle->getModel()?>" name="model" id="model"  class="form-control">
    <br>

    <label for="year">Ano</label>
    <input type="text" value="<?=$vehicle->getYear()?>" name="year" id="year"  class="form-control">
    <br>

    <label for="mileage">KM</label>
    <input type="text" value="<?=$vehicle->getMileage()?>" name="mileage" id="mileage"  class="form-control">
    <br>

    <label for="plate">Placa</label>
    <input type="text" value="<?=$vehicle->getPlate()?>" name="plate" id="plate" class="form-control">
    <br>

    <button type="button" class="btn btn-primary btn-lg">Enviar</button>
</form>