<section class="row mt-5 card-designer">
    <div class="col-md-12">
        <h4 class="card-title">Adicionar Vagas</h4>
    </div>
    <div class="col-md-12">
        <div class="card card-body text-center">
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead class="bg-primary text-white">
                    <tr>
                        <th>Titulo</th>
                        <th>Status</th>
                        <th>Perfis interessados</th>
                        <th>Data</th>
                        <th>Detalhes</th>
                        <th>Editar</th>
                        <th>Excluir</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th>Bla bla</th>
                        <th>Bla bla</th>
                        <th>OK</th>
                        <th>01/01/0101</th>
                        <th>
                            <a class="btn btn-light">Detalhes</a>
                        </th>
                        <th>
                            <a class="btn btn-warning">Editar</a>
                        </th>
                        <th>
                            <button class="btn btn-danger">Excluir</button>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>